### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by awinogradov** [bem/webpack-bem-plugin#2]

**Comment by Vittly** [comment]
Do after https://github.com/bem/webpack-bem-plugin/issues/3 and https://github.com/bem/webpack-bem-plugin/issues/11. Don't forget to check success of `npm run build-examples`. Full testing of examples is too expansive so lets test only build script

**Comment by Vittly** [comment]
Need to check commit messages match to https://seesparkbox.com/foundry/semantic_commit_messages
